### ISSUE TITLE
Encrypted volumes

### ISSUE THREAD

**Issue by novushealth** [npalm/terraform-aws-gitlab-runner#162]
Hi Can someone tell me how can the  runner and the docker-runners can be created with encrypted volumes?

**Comment by npalm** [comment]
@novushealth for the runner we could update root_block_device in the aws launch configuration to encrypt the volume. For the docker runners the only option I see is to encrypt the docker-machine AMI and use that AMI instead of the default one. The aws docker machine driver has no option te enable encryption.

**Comment by novushealth** [comment]
Thanks for the answer. In my case I end up enabling the "Always encrypt new EBS volumes" setting on the ECS Settings page. After doing this, all new instance volumes get encrypted at creation time.
Thanks again

**Comment by npalm** [comment]
@novushealth thx for the feeback, I guess you mean EC2 console (https://eu-west-1.console.aws.amazon.com/ec2/home#EC2Settings:)

Shall we close the issue?

**Comment by npalm** [comment]
And the terraform way

```
resource "aws_ebs_encryption_by_default" "example" {
  enabled = true
}```

**Comment by novushealth** [comment]
Yes, you can close the issue. Thanks
