### ISSUE TITLE
cloud-init fails in eu-west-3

### ISSUE THREAD

**Issue by err0r500** [npalm/terraform-aws-gitlab-runner#194]
Hello,
I first tried to overridre the default region with `eu-west-3` and noticed the runner wan't registreing my gitlab instance.
The reason was that cloud-init failed. I tried with the default `eu-west-1` region and everything worked fine. 
My hypothesis is that the wrong ami is picked in `eu-west-3`.

**Comment by npalm** [comment]
@err0r500 I doubt that the AMI is the problem, we use an AMI filter to find the right AMI. So there is no map or hardcoded AMI. Can you share the error?

**Comment by npalm** [comment]
@err0r500 did you had time to have a look on my question?

**Comment by err0r500** [comment]
Hi Niek,
I was working on something else these days and it was more a heads up than anything else (because `eu-west-1` was actually fine too) .
I try again today and keep you updated

**Comment by npalm** [comment]
Thanks for the update, no hurries

**Comment by npalm** [comment]
@err0r500 I also tried eu-west-3, which was failing on creating a bucket. The problem was that I had used the bucket with the same name minutes before in eu-west-1. After enforcing a fresh bucket name by setting `cache_bucket_prefix` the problem was resolved. The module offers some variables to get more control of the bucket name. 

Shall we close the issue?
