### ISSUE TITLE
Feature request: GitHUB self-hosted runners

### ISSUE THREAD

**Issue by bishtawi** [npalm/terraform-aws-gitlab-runner#220]
So this is obviously a huge undertaking and would live in its own git repo but I figured I would open up an issue here and start the discussion.

GitHUB (not GitLAB) now supports [self hosted runners](https://help.github.com/en/actions/hosting-your-own-runners). It would be nice to get a Terraform AWS module to bring up Github runners similar to how this module brings up Gitlab runners.

**Comment by npalm** [comment]
Would be great to have a elastic setup on spot for the github runners. I did a already some experiments, see https://github.com/npalm/gh-runner-aws-spot-experiment . And we actually already working on a set up. Hopefully release this in the next 2 to 3 weeks.

Since this issue is not related to the GitLab runner I will close it. Thanks for the sugges. I will update the issue once we release the github version.

**Comment by npalm** [comment]
@bishtawi see https://github.com/philips-labs/terraform-aws-github-runner I am just finializing the a branch after which the module is ready to test.
