### ISSUE TITLE
Error putting IAM role policy, and Error attaching policy on creation

### ISSUE THREAD

**Issue by webyneter** [npalm/terraform-aws-gitlab-runner#591]
I'm using version `5.5.0` of the `npalm/gitlab-runner/aws` module.

When instantiating a `npalm/gitlab-runner/aws` module, almost all resources are getting created, except for these two:

```tf
Error: Error putting IAM role policy gitlab-runners-instance-role: NoSuchEntity: The role with name gitlab-runners-instance cannot be found. status code: 404, request id: b86fa6e7-1f54-47c2-89d2-020f7c747c81
with module.gitlab_runner.aws_iam_role_policy.instance[0]
on .terraform/modules/gitlab_runner/logging.tf line 1, in resource "aws_iam_role_policy" "instance":
resource "aws_iam_role_policy" "instance" {
```

```tf
Error: Error attaching policy arn:aws:iam::091232145884:policy/amberatung-gitlab-runners-docker-machine-cache to IAM Role gitlab-runners-instance: NoSuchEntity: The role with name gitlab-runners-instance cannot be found. status code: 404, request id: 65e813ca-5b00-4033-b2bc-22bcf20f375a
with module.gitlab_runner.aws_iam_role_policy_attachment.docker_machine_cache_instance[0]
on .terraform/modules/gitlab_runner/main.tf line 399, in resource "aws_iam_role_policy_attachment" "docker_machine_cache_instance":
resource "aws_iam_role_policy_attachment" "docker_machine_cache_instance" {
```

Yet, none of these errors come up on the second run, and the plan gets applied successfully.

**Comment by mark-webster-catalyst** [comment]
I'm seeing this issue too. Terraform 1.1. Immediately running apply again successfully applies the 2 missing items.

**Comment by gecube** [comment]
The same issue

**Comment by npalm** [comment]
Same here, applying twice is the quick fix.

**Comment by npalm** [comment]
Problem is caused since the iam role could be managed outside the module. In that case the attachements will work, since the role should be exists. In case the module is creating the role, terraform does not know that it should wait for the role. It seems `depends_on` cannot be conditional. So to me the only option is defining the attachments twice. One time in case the role is amanged and one time if the rule is unmanaged. In that case terraform can link the attachments and avoids attachement is done before creation. 

Anyone a better idea?

**Comment by nathan-gilbert** [comment]
Any updates on this issue? I'm seeing this too on creation.

**Comment by kayman-mk** [comment]
I tested #659 in my system. Everything worked with the first apply. Current workaround is to apply the plan twice.
